# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dyllon Gagnier
email: dyllongagnier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site containing various client side JavaScript apps and the musings of a
  programmer/philosopher (though a poor one of both proffessions).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slaymaker1907.github.io" # the base hostname & protocol for your site
github_username:  slaymaker1907

# Build settings
markdown: kramdown
